# Generated by Django 4.1.6 on 2023-02-04 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('Places_id', models.AutoField(primary_key=True, serialize=False)),
                ('meters', models.IntegerField()),
                ('year', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('url', models.URLField()),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Places',
            },
        ),
    ]
